import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

type Student={id:string;name:string;circleId:string};
type Attendance={studentId:string;status:'present'|'absent'};
type Session={id:string;date:string;hours:number;attendance:Attendance[]};
type Circle={id:string;name:string;teacher:string;sessions:Session[]};
type DB={circles:Circle[];students:Student[]};
type RootStackParamList={Home:undefined;Circle:{id:string};AddCircle:undefined;Students:{circleId:string};AddStudent:{circleId:string};Session:{circleId:string};Reports:undefined};
const Stack=createNativeStackNavigator<RootStackParamList>();
const KEY='dawrat_ahl_alquran_v2';
const today=()=>new Date().toISOString().slice(0,10);
const emptyDB:DB={circles:[],students:[]};
const DataContext=React.createContext<{db:DB;setDb:React.Dispatch<React.SetStateAction<DB>>}|null>(null);
function useData(){const c=React.useContext(DataContext);if(!c)throw new Error('missing');return c;}
function Btn({title,onPress,secondary=false}:{title:string;onPress:()=>void;secondary?:boolean}){return <Pressable style={[s.btn,secondary&&s.btn2]} onPress={onPress}><Text style={[s.btnText,secondary&&s.btnText2]}>{title}</Text></Pressable>}
function Input({label,...p}:any){return <View style={{marginBottom:13}}><Text style={s.label}>{label}</Text><TextInput style={s.input} {...p}/></View>}
function Stat({title,value}:{title:string;value:string}){return <View style={s.stat}><Text style={s.statNum}>{value}</Text><Text style={s.muted}>{title}</Text></View>}
function Home({navigation}:any){const {db}=useData();const now=today().slice(0,7);const rows=db.circles.map(c=>c.sessions.filter(x=>x.date.startsWith(now)));const hours=rows.flat().reduce((a,x)=>a+x.hours,0);const attendance=rows.flat().reduce((a,x)=>a+x.attendance.filter(v=>v.status==='present').length,0);return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.brand}>دورة أهل القرآن</Text><Text style={s.sub}>لوحة الإدارة</Text><View style={s.stats}><Stat title="الحلقات" value={String(db.circles.length)}/><Stat title="ساعات الشهر" value={String(hours)}/><Stat title="الحضور" value={String(attendance)}/></View><Btn title="➕ إضافة حلقة" onPress={()=>navigation.navigate('AddCircle')}/><Btn title="📊 التقرير الشهري" onPress={()=>navigation.navigate('Reports')} secondary/><Text style={s.section}>الحلقات</Text>{db.circles.length===0?<Text style={s.empty}>أضف أول حلقة للبدء.</Text>:db.circles.map(c=><Pressable key={c.id} style={s.card} onPress={()=>navigation.navigate('Circle',{id:c.id})}><Text style={s.cardTitle}>{c.name}</Text><Text style={s.muted}>المدرس: {c.teacher||'—'} · الطلاب: {db.students.filter(x=>x.circleId===c.id).length}</Text></Pressable>)}</ScrollView></SafeAreaView>}
function AddCircle({navigation}:any){const {db,setDb}=useData();const [name,setName]=useState('');const [teacher,setTeacher]=useState('');return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>إضافة حلقة</Text><Input label="اسم الحلقة" value={name} onChangeText={setName} placeholder="مثال: حلقة الفجر"/><Input label="اسم المدرس" value={teacher} onChangeText={setTeacher}/><Btn title="حفظ الحلقة" onPress={()=>{if(!name.trim())return Alert.alert('تنبيه','اكتب اسم الحلقة');setDb({...db,circles:[...db.circles,{id:Date.now().toString(),name:name.trim(),teacher:teacher.trim(),sessions:[]}]});navigation.goBack()}}/></ScrollView></SafeAreaView>}
function CircleScreen({route,navigation}:any){const {db}=useData();const c=db.circles.find(x=>x.id===route.params.id);if(!c)return null;const students=db.students.filter(x=>x.circleId===c.id);const hours=c.sessions.reduce((a,x)=>a+x.hours,0);const present=c.sessions.reduce((a,x)=>a+x.attendance.filter(v=>v.status==='present').length,0);return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>{c.name}</Text><Text style={s.muted}>المدرس: {c.teacher||'—'}</Text><View style={s.stats}><Stat title="الساعات" value={String(hours)}/><Stat title="الحضور" value={String(present)}/><Stat title="الطلاب" value={String(students.length)}/></View><Btn title="👨‍🎓 إدارة الطلاب" onPress={()=>navigation.navigate('Students',{circleId:c.id})}/><Btn title="✅ تسجيل حضور اليوم" onPress={()=>navigation.navigate('Session',{circleId:c.id})}/><Text style={s.section}>آخر الجلسات</Text>{c.sessions.slice().reverse().map(x=><View style={s.card} key={x.id}><Text style={s.cardTitle}>{x.date}</Text><Text style={s.muted}>{x.hours} ساعة · حضور {x.attendance.filter(v=>v.status==='present').length} · غياب {x.attendance.filter(v=>v.status==='absent').length}</Text></View>)}</ScrollView></SafeAreaView>}
function Students({route,navigation}:any){const {db}=useData();const list=db.students.filter(x=>x.circleId===route.params.circleId);return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>طلاب الحلقة</Text><Btn title="➕ إضافة طالب" onPress={()=>navigation.navigate('AddStudent',{circleId:route.params.circleId})}/>{list.length===0?<Text style={s.empty}>لا يوجد طلاب بعد.</Text>:list.map((x,i)=><View style={s.card} key={x.id}><Text style={s.cardTitle}>{i+1}. {x.name}</Text></View>)}</ScrollView></SafeAreaView>}
function AddStudent({route,navigation}:any){const {db,setDb}=useData();const [name,setName]=useState('');return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>إضافة طالب</Text><Input label="اسم الطالب" value={name} onChangeText={setName}/><Btn title="حفظ الطالب" onPress={()=>{if(!name.trim())return Alert.alert('تنبيه','اكتب اسم الطالب');setDb({...db,students:[...db.students,{id:Date.now().toString(),name:name.trim(),circleId:route.params.circleId}]});navigation.goBack()}}/></ScrollView></SafeAreaView>}
function Session({route,navigation}:any){const {db,setDb}=useData();const c=db.circles.find(x=>x.id===route.params.circleId);const students=db.students.filter(x=>x.circleId===route.params.circleId);const [date,setDate]=useState(today());const [hours,setHours]=useState('2');const [statuses,setStatuses]=useState<Record<string,'present'|'absent'>>({});if(!c)return null;const toggle=(id:string)=>setStatuses(x=>({...x,[id]:x[id]==='present'?'absent':'present'}));const present=students.filter(x=>statuses[x.id]==='present').length;return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>حضور {c.name}</Text><Input label="التاريخ" value={date} onChangeText={setDate}/><Input label="مدة الحلقة بالساعات" value={hours} onChangeText={setHours} keyboardType="decimal-pad"/><Text style={s.section}>الحضور — {present} طالب</Text>{students.length===0?<Text style={s.empty}>أضف الطلاب أولًا.</Text>:students.map(st=><Pressable key={st.id} style={[s.attRow,statuses[st.id]==='present'?s.present:s.absent]} onPress={()=>toggle(st.id)}><Text style={s.attName}>{st.name}</Text><Text style={s.attStatus}>{statuses[st.id]==='present'?'حاضر':'غائب'}</Text></Pressable>)}<Btn title="💾 حفظ جلسة اليوم" onPress={()=>{const h=Number(hours);if(!date||!Number.isFinite(h)||h<=0)return Alert.alert('تنبيه','راجع التاريخ والساعات');const attendance=students.map(st=>({studentId:st.id,status:statuses[st.id]||'absent'} as Attendance));setDb({...db,circles:db.circles.map(x=>x.id===c.id?{...x,sessions:[...x.sessions,{id:Date.now().toString(),date,hours:h,attendance}]}:x)});navigation.goBack()}}/></ScrollView></SafeAreaView>}
function Reports(){const {db}=useData();const [month,setMonth]=useState(today().slice(0,7));const rows=useMemo(()=>db.circles.map(c=>{const ss=c.sessions.filter(x=>x.date.startsWith(month));return{name:c.name,sessions:ss.length,hours:ss.reduce((a,x)=>a+x.hours,0),present:ss.reduce((a,x)=>a+x.attendance.filter(v=>v.status==='present').length,0),absent:ss.reduce((a,x)=>a+x.attendance.filter(v=>v.status==='absent').length,0)}}),[db,month]);const total=rows.reduce((a,x)=>({sessions:a.sessions+x.sessions,hours:a.hours+x.hours,present:a.present+x.present,absent:a.absent+x.absent}),{sessions:0,hours:0,present:0,absent:0});return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>التقرير الشهري</Text><Input label="الشهر YYYY-MM" value={month} onChangeText={setMonth}/><View style={s.card}><Text style={s.cardTitle}>إجمالي الدورة</Text><Text style={s.report}>⏱ {total.hours} ساعة</Text><Text style={s.report}>👥 {total.present} حضور</Text><Text style={s.report}>❌ {total.absent} غياب</Text><Text style={s.report}>📅 {total.sessions} جلسة</Text></View>{rows.map(r=><View style={s.card} key={r.name}><Text style={s.cardTitle}>{r.name}</Text><Text style={s.muted}>⏱ {r.hours} ساعة · 👥 {r.present} حضور · ❌ {r.absent} غياب · 📅 {r.sessions} جلسة</Text></View>)}</ScrollView></SafeAreaView>}
function App(){const [db,setDb]=useState<DB>(emptyDB);const [ready,setReady]=useState(false);useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>{if(x)setDb(JSON.parse(x));setReady(true)})},[]);useEffect(()=>{if(ready)AsyncStorage.setItem(KEY,JSON.stringify(db))},[db,ready]);return <DataContext.Provider value={{db,setDb}}><NavigationContainer><Stack.Navigator screenOptions={{headerTitle:'دورة أهل القرآن',headerBackTitle:'رجوع'}}><Stack.Screen name="Home" component={Home} options={{headerShown:false}}/><Stack.Screen name="AddCircle" component={AddCircle}/><Stack.Screen name="Circle" component={CircleScreen}/><Stack.Screen name="Students" component={Students}/><Stack.Screen name="AddStudent" component={AddStudent}/><Stack.Screen name="Session" component={Session}/><Stack.Screen name="Reports" component={Reports}/></Stack.Navigator></NavigationContainer></DataContext.Provider>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#f7f4ec'},pad:{padding:18,paddingBottom:50},brand:{fontSize:31,fontWeight:'800',textAlign:'center',color:'#6f5b24',marginTop:18},sub:{textAlign:'center',color:'#777',marginBottom:20},stats:{flexDirection:'row',gap:8,marginBottom:16},stat:{flex:1,backgroundColor:'#fff',borderRadius:14,padding:13,alignItems:'center',borderWidth:1,borderColor:'#e6dfcf'},statNum:{fontSize:23,fontWeight:'800',color:'#6f5b24'},muted:{color:'#777',marginTop:4},btn:{backgroundColor:'#7b6425',padding:15,borderRadius:12,alignItems:'center',marginBottom:11},btn2:{backgroundColor:'#fff',borderWidth:1,borderColor:'#7b6425'},btnText:{color:'#fff',fontSize:17,fontWeight:'700'},btnText2:{color:'#7b6425'},section:{fontSize:21,fontWeight:'800',marginVertical:12,color:'#333'},card:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:10,borderWidth:1,borderColor:'#e6dfcf'},cardTitle:{fontSize:18,fontWeight:'800',color:'#333'},empty:{textAlign:'center',color:'#888',padding:30},h1:{fontSize:27,fontWeight:'800',color:'#333',marginBottom:16},label:{fontWeight:'700',marginBottom:7,color:'#444'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:10,padding:13,fontSize:16,textAlign:'right'},report:{fontSize:18,fontWeight:'700',marginTop:8,color:'#444'},attRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:15,borderRadius:12,marginBottom:8,borderWidth:1},present:{backgroundColor:'#e8f5e9',borderColor:'#9ccc65'},absent:{backgroundColor:'#fff',borderColor:'#ddd'},attName:{fontSize:17,fontWeight:'700'},attStatus:{fontWeight:'800',color:'#555'}});
export default App;
